
spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper_custom/*.xml
  type-aliases-package: com.hengxunda.dao.entity

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

 # 短信配置
sms:
  smsCode:
    #短信验证码过期时间（5分钟）
    expireTime: 5
  #短信url
  url: http://47.92.119.47/sms