
spring:
  profiles:
    active: dev
#  datasource:
#    druid:
#      web-stat-filter:
#        url-pattern: /*
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#      stat-view-servlet:
#        url-pattern: /druid/*
#        reset-enable: false
#        login-username: blockDruid
#        login-password: block@2018
#        allow:
#        deny:

mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper_custom/*.xml
  type-aliases-package: com.hengxunda.dao.entity

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql