

online: true

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.5:3306/blockbank?autoReconnect=true&maxReconnects=10&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&transformedBitIsBoolean=true&zeroDateTimeBehavior=convertToNull&serverTimezone=PRC&useSSL=false&useAffectedRows=true
    username: block
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 5
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'MQ' FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  redis:
    host: 192.168.0.6
    port: 6379
    password:
    jedis:
      pool:
        max-active: 10
        max-idle: 10
    timeout: 60000

redisson:
  address: redis://192.168.0.19:6379
  password:

sms:
  smsCode:
    #短信验证码过期时间（5分钟）
    expireTime: 5
  #短信url
  url: http://47.92.118.152/msg
  # 每天短信限制条数
  smsCountLimit: 30